openapi: 3.0.3
info:
  title: Anime Info Api
  description: A very simple OAS Provider contract
  version: 1.0.0
  contact:
    name: Pollito
    url: https://pollitodev.netlify.app/
servers:
  - url: 'http://localhost:8080'
paths:
  /anime:
    get:
      tags:
        - Anime
      summary: Given My Anime List id, gets name and year of the anime
      operationId: getAnimeInfo
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
          description: My Anime List id
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimeInfo'

        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    AnimeInfo:
      type: object
      properties:
        name:
          type: string
        year:
          type: integer
    Error:
      type: object
      properties:
        timestamp:
          type: string
          description: The date and time when the error occurred in ISO 8601 format.
          format: date-time
          example: "2024-01-04T15:30:00Z"
        session:
          type: string
          format: uuid
          description: A unique UUID for the session instance where the error happened, useful for tracking and debugging purposes.
        error:
          type: string
          description: A brief error message or identifier.
        message:
          type: string
          description: A detailed error message.
        path:
          type: string
          description: The path that resulted in the error.